# Generated by Django 2.2.7 on 2019-11-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('A', 'ACTIVA'), ('I', 'INACTIVO')], default='A', max_length=1)),
            ],
        ),
    ]
