# Generated by Django 2.2.7 on 2019-11-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seccionGrado', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='seccionGrado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seccionGrado.SeccionGrado'),
        ),
    ]
