# Generated by Django 2.2.7 on 2019-11-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amonestacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amonestacion',
            name='horario',
        ),
    ]
