# Generated by Django 2.2.7 on 2019-11-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuntualidad',
            fields=[
                ('idImpuntualidad', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('J', 'JUSTIFICADA'), ('I', 'INJUSTIFICADA')], default='I', max_length=1)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
            ],
        ),
    ]
