# Generated by Django 2.2.7 on 2019-12-03 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuntualidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impuntualidad',
            old_name='fechaHora',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='impuntualidad',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2019, 12, 3, 0, 39, 0, 517443)),
        ),
    ]
