# Generated by Django 2.2.7 on 2019-12-03 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impuntualidad', '0002_auto_20191202_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuntualidad',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='impuntualidad',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2019, 12, 3, 0, 54, 0, 449879)),
        ),
    ]
