# Generated by Django 2.2.7 on 2019-11-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('codigo', models.CharField(max_length=240, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante')),
                ('personal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
