# Generated by Django 2.2.7 on 2019-11-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0001_initial'),
        ('usuario', '0002_auto_20191114_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permiso.Permiso'),
        ),
    ]
