# Generated by Django 2.2.7 on 2019-11-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoFalta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('idFalta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'ACTIVA'), ('I', 'INACTIVA')], default='A', max_length=1)),
                ('tipoFalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoFalta.TipoFalta')),
            ],
        ),
    ]
