# Generated by Django 2.2.7 on 2019-11-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidad', '0001_initial'),
        ('grado', '0001_initial'),
        ('personal', '0001_initial'),
        ('seccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionGrado',
            fields=[
                ('idSeccionGrado', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino')], default='M', max_length=1)),
                ('anio', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidad.Especialidad')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grado.Grado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccion.Seccion')),
            ],
        ),
    ]
