# Generated by Django 2.2.7 on 2019-11-27 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seccionGrado', '0001_initial'),
        ('inasistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaGrado',
            fields=[
                ('idAsistenciaGrado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('seccionGrado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seccionGrado.SeccionGrado')),
            ],
        ),
    ]
