# Generated by Django 2.2.7 on 2019-11-28 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasistencia', '0002_asistenciagrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciagrado',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 11, 27)),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 11, 27)),
        ),
    ]
