# Generated by Django 2.2.4 on 2019-12-01 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasistencia', '0003_auto_20191127_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciagrado',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 12, 1)),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 12, 1)),
        ),
    ]
