# Generated by Django 2.2.6 on 2019-12-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inasistencia', '0004_auto_20191201_1210'),
        ('inasistencia', '0004_auto_20191201_2249'),
    ]

    operations = [
    ]
