# Generated by Django 2.2.7 on 2019-12-03 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inasistencia', '0005_merge_20191202_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciagrado',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='fecha',
            field=models.DateField(default=datetime.date(2019, 12, 2)),
        ),
    ]
