# Generated by Django 2.2.7 on 2019-11-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seccionGrado', '0001_initial'),
        ('personal', '0001_initial'),
        ('asignatura', '0001_initial'),
        ('tiempo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraClase',
            fields=[
                ('idHoraClase', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('L', 'LUNES'), ('M', 'MARTES'), ('X', 'MIÉRCOLES'), ('J', 'JUEVES'), ('V', 'VIERNES')], default='L', max_length=1)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.Asignatura')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
                ('seccionGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccionGrado.SeccionGrado')),
                ('tiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiempo.Tiempo')),
            ],
        ),
    ]
