# Generated by Django 2.2.7 on 2019-11-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('idPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('A', 'ACTIVA'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('modulo', models.ManyToManyField(to='modulo.Modulo')),
            ],
        ),
    ]
